use guessWho;
db.dropDatabase();

db.characters.insertMany(
  [
    {
      name: 'Amy',
      inplay: 'true',
      image_url: '../e29_imgages/amy.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'true',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Maria',
      inplay: 'true',
      image_url: '../e29_imgages/maria.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'true',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Mark King',
      inplay: 'true',
      image_url: '../e29_imgages/markk.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'true',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'true',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'David',
      inplay: 'true',
      image_url: '../e29_imgages/david.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'true',
      noise: 'true',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Pim',
      inplay: 'true',
      image_url: '../e29_imgages/pim.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'true',
      vape: 'false',
      nickname: 'true',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Eric',
      inplay: 'true',
      image_url: '../e29_imgages/eric.png',
      hair_colour: 'blonde',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Grant',
      inplay: 'true',
      image_url: '../e29_imgages/grant.png',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Alasdair',
      inplay: 'true',
      image_url: '../e29_imgages/alasdair.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'true',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Emily',
      inplay: 'true',
      image_url: '../e29_imgages/emily.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'true',
      smile: 'true'
    },
    {
      name: 'Mark Mackay',
      inplay: 'true',
      image_url: '../e29_imgages/markm.png',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Charlie',
      inplay: 'true',
      image_url: '../e29_imgages/charlie.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Rory',
      inplay: 'true',
      image_url: '../e29_imgages/rory.png',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'true',
      standup: 'false',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Stephen',
      inplay: 'true',
      image_url: '../e29_imgages/stephen.png',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'true',
      standup: 'false',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Colin',
      inplay: 'true',
      image_url: '../e29_imgages/colin.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'true',
      smile: 'false'
    },
    {
      name: 'Lidia',
      inplay: 'true',
      image_url: '../e29_imgages/lidia.png',
      hair_colour: 'red',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Pawel',
      inplay: 'true',
      image_url: '../e29_imgages/pawel.png',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'true',
      earring: 'true',
      employee: 'true',
      smile: 'false'
    },
    {
      name: 'Ben',
      inplay: 'true',
      image_url: '../e29_imgages/ben.png',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'true',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Jon',
      inplay: 'true',
      image_url: '../e29_imgages/jon.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'true',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'true',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Jarrod',
      inplay: 'true',
      image_url: '../e29_imgages/jarrod.png',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'true',
      employee: 'true',
      smile: 'false'
    },
    {
      name: 'Rob',
      inplay: 'true',
      image_url: '../e29_imgages/rob.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Jenn',
      inplay: 'true',
      image_url: '../e29_imgages/jenn.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Matt',
      inplay: 'true',
      image_url: '../e29_imgages/matt.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Annabel',
      inplay: 'true',
      image_url: '../e29_imgages/annabel.png',
      hair_colour: 'red',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Juan',
      inplay: 'true',
      image_url: '../e29_imgages/juan.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'true',
      smile: 'true'
    },
    {
      name: 'Jordan',
      inplay: 'true',
      image_url: '../e29_imgages/jordan.png',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'true',
      earring: 'false',
      employee: 'true',
      smile: 'true'
    },
    {
      name: 'Kat',
      inplay: 'true',
      image_url: '../e29_imgages/kat.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    },
    {
      name: 'Myriam',
      inplay: 'true',
      image_url: '../e29_imgages/myriam.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false',
      noise: 'false',
      earring: 'true',
      employee: 'false',
      smile: 'false'
    },
    {
      name: 'Becky',
      inplay: 'true',
      image_url: '../e29_imgages/becky.png',
      hair_colour: 'blonde',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false',
      noise: 'false',
      earring: 'false',
      employee: 'false',
      smile: 'true'
    }
  ]
);

db.questions.insertMany(
  [
    {
      id: 1,
      question: "Is the character a female?",
      related_key: "gender",
      attribute: "f"
    },
    {
      id: 2,
      question: "Is the character a male?",
      related_key: "gender",
      attribute: "m"
    },
    {
      id: 3,
      question: "Does the character have brunette hair?",
      related_key: "hair_colour",
      attribute: "brunette"
    },
    {
      id: 4,
      question: "Does the character have blonde hair?",
      related_key: "hair_colour",
      attribute: "blonde"
    },
    {
      id: 5,
      question: "Does the character have red hair?",
      related_key: "hair_colour",
      attribute: "red"
    },
    {
      id: 6,
      question: "Does the character shave their hair",
      related_key: "hair_colour",
      attribute: "shaved"
    },
    {
      id: 7,
      question: "Does your chracter have a big smile?",
      related_key: "smile",
      attribute: "true"
    },
    {
      id: 8,
      question: "Is the character wearing glasses?",
      related_key: "glasses",
      attribute: "true"
    },
    {
      id: 9,
      question: "Does your character have an earring?",
      related_key: "earring",
      attribute: "true"
    },
    {
      id: 10,
      question: "Does the character have facial hair?",
      related_key: "facial_hair",
      attribute: "true"
    },
    {
      id: 11,
      question: "Does your character work at CodeClan?",
      related_key: "employee",
      attribute: "true"
    },
    {
      id: 12,
      question: "Is the character a member of crumbsCollaborate?",
      related_key: "crumbs",
      attribute: "true"
    },
    {
      id: 13,
      question: "Does the character come from the UK?",
      related_key: "uk",
      attribute: "true"
    },
    {
      id: 14,
      question: "Is the character on time for standup?",
      related_key: "standup",
      attribute: "true"
    },
    {
      id: 15,
      question: "Does the character have vape between classes?",
      related_key: "vape",
      attribute: "true"
    },
    {
      id: 16,
      question: "Does the character have a class nickname?",
      related_key: "nickname",
      attribute: "true"
    },
    {
      id: 17,
      question: "Does your character express themselves in strange noises?",
      related_key: "noises",
      attribute: "true"
    },
    {
      id: 18,
      question: "Does the character get into the pubquiz rivalry with e28?",
      related_key: "pubquiz",
      attribute: "true"
    },
    {
      id: 19,
      question: "Does the character have a model photo?",
      related_key: "model",
      attribute: "true"
    },
    {
      id: 20,
      question: "Does the character have a secret doublelife as a singer?",
      related_key: "singer",
      attribute: "true"
    }
  ]
);
