use guessWho;
db.dropDatabase();

db.characters.insertMany(
  [
    {
      name: 'Amy',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'true'
    },
    {
      name: 'Maria',
      inplay: 'true',
      image_url: '../images/maria29.png',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'true'
    },
    {
      name: 'Mark King',
      inplay: 'true',
      image_url: '../images/markk29.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'true',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'true'
    },
    {
      name: 'David',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'true'
    },
    {
      name: 'Pim',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'true',
      vape: 'false',
      nickname: 'true',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Eric',
      inplay: 'true',
      image_url: '',
      hair_colour: 'blonde',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Grant',
      inplay: 'true',
      image_url: '',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Alasdair',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Emily',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Mark Mackay',
      inplay: 'true',
      image_url: '',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Charlie',
      inplay: 'true',
      image_url: '../images/charlie29.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Rory',
      inplay: 'true',
      image_url: '',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'true',
      vape: 'false',
      nickname: 'true',
      standup: 'false',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Stephen',
      inplay: 'true',
      image_url: '',
      hair_colour: 'shaved',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'true',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'true',
      standup: 'false',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Lidia',
      inplay: 'true',
      image_url: '',
      hair_colour: 'red',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Ben',
      inplay: 'true',
      image_url: '',
      hair_colour: 'red',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Jon',
      inplay: 'true',
      image_url: '../images/jon29.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'true',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Rob',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Jenn',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Matt',
      inplay: 'true',
      image_url: '../images/matt29.png',
      hair_colour: 'brunette',
      gender: 'm',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'true',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Annabel',
      inplay: 'true',
      image_url: '',
      hair_colour: 'red',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'false',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Kat',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'true',
      pubquiz: 'false',
      crumbs: 'false'
    },
    {
      name: 'Myriam',
      inplay: 'true',
      image_url: '',
      hair_colour: 'brunette',
      gender: 'f',
      glasses: 'true',
      facial_hair: 'false',
      uk: 'false',
      singer: 'false',
      vape: 'true',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'true',
      crumbs: 'false'
    },
    {
      name: 'Becky',
      inplay: 'true',
      image_url: '',
      hair_colour: 'blonde',
      gender: 'f',
      glasses: 'false',
      facial_hair: 'false',
      uk: 'true',
      singer: 'false',
      vape: 'false',
      nickname: 'false',
      standup: 'true',
      model: 'false',
      pubquiz: 'false',
      crumbs: 'false'
    }
  ]
);

db.questions.insertMany(
  [
    {
      id: 1,
      question: "Is the character a female?",
      related_key: "gender",
      attribute: "f"
    },
    {
      id: 2,
      question: "Is the character a male?",
      related_key: "gender",
      attribute: "m"
    },
    {
      id: 3,
      question: "Does the character have brunette hair?",
      related_key: "hair_colour",
      attribute: "brown"
    },
    {
      id: 4,
      question: "Does the character have blonde hair?",
      related_key: "hair_colour",
      attribute: "blonde"
    },
    {
      id: 5,
      question: "Does the character have red hair?",
      related_key: "hair_colour",
      attribute: "red"
    },
    {
      id: 6,
      question: "Does the character shave their hair",
      related_key: "hair_colour",
      attribute: "shaved"
    },
    {
      id: 7,
      question: "Is the character wearing glasses?",
      related_key: "glasses",
      attribute: "true"
    },
    {
      id: 8,
      question: "Does the character have facial hair?",
      related_key: "facial_hair",
      attribute: "true"
    },
    {
      id: 9,
      question: "Does the character come from the UK?",
      related_key: "UK",
      attribute: "true"
    },
    {
      id: 10,
      question: "Is the character a member of crumbsCollaborate?",
      related_key: "crumbs",
      attribute: "true"
    },
    {
      id: 11,
      question: "Does the character get into the pubquiz rivalry with e28?",
      related_key: "pubquiz",
      attribute: "true"
    },
    {
      id: 12,
      question: "Does the character have a secret doublelife as a singer?",
      related_key: "singer",
      attribute: "true"
    },
    {
      id: 13,
      question: "Does the character have vape between classes?",
      related_key: "vape",
      attribute: "true"
    },
    {
      id: 14,
      question: "Does the character have a class nickname?",
      related_key: "nickname",
      attribute: "true"
    },
    {
      id: 15,
      question: "Is the character on time for standup?",
      related_key: "standup",
      attribute: "true"
    },
    {
      id: 16,
      question: "Does the character have a model photo?",
      related_key: "model",
      attribute: "true"
    }
    //strange noises, earrings, code clan employee, smiley?
  ]
);
